### ISSUE TITLE
AJAX links randomly stop working on the site

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#101]
I've noticed that more than once. One day all JS AJAX links were breaking on the production server, while they were fine on my machine. I just clicked on the `Hi there! If you'd like to tell us your name, go ahead and click here. Otherwise, go ahead and start having fun!` notice and it loaded the profile fine in a modal first. Then I went to profile (on roomiesapp.com) and back to the corkboard. This time the link loaded the actual profile page instead of a modal. Very odd.

**Comment by turtleguyyy** [comment]
I can only assume there is some other js bug that stops all js from running. If it happens again, open up the console and see if it's yelling at you. :)
