### ISSUE TITLE
New Feature (time allowing)

### ISSUE THREAD

**Issue by alyssamichelle** [clevercode/roomies#121]
What do you think about a "List" feature? You can create a grocery list that all house members can access and log onto when they're at the store, checking off items they purchased??

**Comment by olivierlacan** [comment]
No new features until everything we set out to do is fixed and ready for prime time. 

No discussion. :-)

**Comment by alyssamichelle** [comment]
is there another area i can input those, since i am working with roomies right now i want to write them out while i rem. them, i totally understand wanting to get what you have working well before adding to it.

**Comment by olivierlacan** [comment]
Pivotal would have been the place to put that in (the icebox). Make a text file, keep them to yourself for now. 

When 1.5 is ready, we'll have a feature brawl, but Issues is for action items, not suggestions. That's not to say I don't welcome suggestions, just not here.

**Comment by turtleguyyy** [comment]
So should be using pivotal for bug tracking as well, or just feature tracking? And if we're only using pivotal for feature tracking, she should add ideas to there, but leave em in the icebox, no?

**Comment by turtleguyyy** [comment]
Totally forgot we had a pivotal account set up for roomies lol

**Comment by turtleguyyy** [comment]
Just checked pivotal. Seems we have a free account which allows for 5 projects and one member. I'll have her just make a text file for now until we figure what we want to do with everything

**Comment by olivierlacan** [comment]
Just reopened and extended the Pivotal account, invited Alyssa.

**Comment by alyssamichelle** [comment]
is pivotal just used as a freezer for ideas or other things as well?

**Comment by olivierlacan** [comment]
Pivotal contains User stories (user should be able to do X).

Icebox: brainstorm
Backlog: needs to be worked on
