### ISSUE TITLE
Witty Flash Notices

### ISSUE THREAD

**Issue by alyssamichelle** [clevercode/roomies#122]
After you create an ass. to someone else it tells you to lend a helping hand, maybe we could put a min. assignment limit of assigning to others before the "helping hand" notice is displayed. For example, after assigning 5 ass. to zach and none to myself, then it should pop-up.

**Comment by olivierlacan** [comment]
Alyssa, stop with the feature creep. There are way too many things breaking and missing right now to be dreaming up new one.
