### ISSUE TITLE
When resetting password, email is required?

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#22]
Weird behavior.
If you request a new password, you receive an email. If you click the link in the email, it takes you to the password#edit controller/view and when you enter your new password (twice) this happens:
http://link.olivierlacan.com/67zF

Don't understand why this requires an email if the user came in with a token but the params don't contain the email apparently, seems silly.

```
Started GET "/users/password/edit?reset_password_token=0baFm0zop7sSg6JNhbUH" for 127.0.0.1 at 2011-04-20 04:02:26 -0400
[Barista] Compiling all scripts for barista
[Barista] Compiling all coffeescripts
  Processing by Devise::PasswordsController#edit as HTML
  Parameters: {"reset_password_token"=>"[FILTERED]"}
```

**Comment by fullsailor** [comment]
You should use the `reset_password_token` to find the user. The `params` will not & should not have the email address.

**Comment by olivierlacan** [comment]
Ok. Will do. Forgot that was stored on the user model.

On Apr 20, 2011, at 11:33 AM, fullsailor
reply@reply.github.com
wrote:
