### ISSUE TITLE
Footer hides page without scrollbar

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#32]
The footer follows the page now but you're going to have to add padding equivalent to the footer's height to the page too ;-)

http://link.olivierlacan.com/6IaQ

**Comment by olivierlacan** [comment]
Another example.
http://link.olivierlacan.com/6O0b

**Comment by olivierlacan** [comment]
Still poses an issue on the home page. 
The footer hides the bottom of the page by default when you log out.

After logging out: 
http://link.olivierlacan.com/6czX

**Comment by turtleguyyy** [comment]
I believe this issue should be fixed, though I don't have a screen big enough to test it. Let me know if it's still not working.

**Comment by olivierlacan** [comment]
Just remote tested on the iMac, works perfect at least on the home page. Nice work buddy.

Olivier Lacan
Sent with Sparrow
