### ISSUE TITLE
Forms that are injected into a model contain non-unique element IDs

### ISSUE THREAD

**Issue by fullsailor** [clevercode/roomies#33]
There are repetitions in `#flash` and `#main` at least.

Could cause some weird JavaScript issues when selecting these elements.

**Comment by turtleguyyy** [comment]
Yeah, I've noticed the issue before, but I couldn't think of any instance when we would need to target those specific id's. With css we can just be specific enough to only target the ones inside #modal, but when would we need to target them with javascript?

**Comment by fullsailor** [comment]
I guess this could go further with, why are those container elements even included in the modal. One trick I use when pulling in those view fragments with jquery is to not render the layout.

Example:

``` ruby
def show
  @item = Item.find(params[:id])
  render :show, :layout => !request.xhr?
end
```

`request.xhr?` returns true if the request came from XMLHttpRequest
