### ISSUE TITLE
Somehow time is erroneous when localized

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#35]
Don't get that one at all, any idea Andrew?
Result : http://link.olivierlacan.com/6Jzr

en.yml locale:
http://link.olivierlacan.com/6Kfg

view: 
http://link.olivierlacan.com/6KVq

**Comment by fullsailor** [comment]
What's the problem?

**Comment by olivierlacan** [comment]
Fixed this ages ago too. Sorry for not responding.
