### ISSUE TITLE
Sign Up form still requires a password

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#4]
A random password should be generated for users as soon as they enter their email address on the home page sign up ("move in") form.

This password should be sent unencrypted via the registration confirmation email (since it's not sensitive yet) for reference.

After the registration is completed the user should be automatically logged in and redirected to the corkboard page where a welcome message should great him.

Right now, this happens: http://link.olivierlacan.com/5xcs

**Comment by fullsailor** [comment]
> This password should be sent unencrypted via the registration confirmation email (since it's not sensitive yet) for reference.

I wouldn't agree that it is "not sensitive" That is the password into their account, which unless you force them to change it upon using it the first time, would continue to be exposed in their inbox.

**Comment by olivierlacan** [comment]
I don't plan on forcing them to change it on their first sign in, no.
So let's just send them a link to change their password if they forgot considering we log them in on sign up and remember them anyway.

Olivier Lacan
Sent with Sparrow
