### ISSUE TITLE
Box-shadows on filter buttons break in Safari

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#49]
Don't know what you changed, I had tested them in every browser before and they worked fine.

![Screenshot](http://f.cl.ly/items/1Z2k3g0U363Z0n2K2J3S/Screen%20shot%202011-05-10%20at%208.01.23%20PM.png)

**Comment by fullsailor** [comment]
Is this still a valid ticket?

**Comment by olivierlacan** [comment]
Sadly.

**Comment by olivierlacan** [comment]
Fixed this.
