### ISSUE TITLE
Assignments listing should be preloaded on Calendar

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#50]
I'm sure you've noticed how slow the AJAX load is on the Calendar popover. I think we should preload all those lists for each day within a div or span directly when we load the corkboard. That way it's simply a matter of revealing the info.

The trick would be to manage either to load everything (regardless of what filter the user is currently using (my or all assignments) or to reload every day as soon as the filter is switched.

**Comment by turtleguyyy** [comment]
Started in on this one then stopped. In order to fix the issue, we'd have to load everything at the beginning like you said and somehow track which lists belong with which days. I'm worried this could be slower and more CPU intensive than loading on click. What you think?

**Comment by olivierlacan** [comment]
Yeah I've had second thoughts on that one. Requesting the grand master @fullsailor's opinion.
Still think we should load everything or find a way to speed up the AJAX call.
By the way, I realized that you were loading full HTML and then stripping layout when we have JSON interface in every controller, what's up with that ? :-p

**Comment by fullsailor** [comment]
1. What's the CPU intensive task we're worried about?
2. What are the two options?
