### ISSUE TITLE
Does a house inviter get notified when his offer is rejected?

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#58]
Important question. Do we use an "ignore" mechanism, or a "refuse" one. I'd rather go for refuse, even if adds a bit of work.
It might end up making sense to have a Message model with actions and information associated with it between two or more users...

**Comment by fullsailor** [comment]
I don't think that this needs too much work. I would use the ignore model simply because an inviter should not send a house invitation to a person that doesn't live with them.

**Comment by olivierlacan** [comment]
Got point.
