### ISSUE TITLE
House invitation & Adding Roomies should have action affordances

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#60]
Several beta testers have mentioned that they had to hunt for buttons to add roomies and eventually found the links in there.
The two actions should be clearly separated, not in the same sentence. And they should be action buttons with clear affordance.

http://link.olivierlacan.com/6s5c

**Comment by turtleguyyy** [comment]
Quick fix for now: http://cl.ly/0k2G0u0s2v352y1e4740

**Comment by olivierlacan** [comment]
Quick fix is nice patchy.

Olivier Lacan
Sent with Sparrow
