### ISSUE TITLE
Load assignments#show from calendars in popover

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#64]
Do this quick please so it doesn't cause confusion with beta testers. 
You're opening the upcoming assignments within a popover but not the assignments listed in the calendars right below.

**Comment by turtleguyyy** [comment]
Which popover are we talking about? There is one that shows upcoming assignments but not assignment in the calendar?

**Comment by olivierlacan** [comment]
No no, just the simple popover you use to display assignments#show when you click on an assignment in Today/Tomorrow/Etc. Go in your calendar, open a list of assignments for a day, and then click on one of them, it will take your to /assignment/ID instead of staying on the corkboard and loading the assignment details (show action) in the popover.
