### ISSUE TITLE
Include Accept House Invitation link in mailer

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#65]
If the email being invited is that of an existing user, we should offer him a quick one-click way to accept (or refuse) the house invitation, by also telling him who invited him. That may involve using something like this:

```
  match '/assignments/:id/confirm'      => 'assignments#confirm'
  match '/assignments/:id/reject'       => 'assignments#reject'
```

Since you wouldn't want every house invitation to be accepted or refused if that specific user has more than one (just being cautious).

See the new mailers I made for how to do this.

**Comment by fullsailor** [comment]
Use the resource routing for this.

``` ruby
resources :assignments do
  member do
    get :confirm
    get :reject
  end
end
```

-- or --

``` ruby
resources :assignments do
  get :confirm :on => :member
  get :reject :on => :member
end
```
