### ISSUE TITLE
Completed assignments for upcoming shouldn't disappear

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#66]
As demonstrated by beta feedback, users are confused when they check off an assignment and it completely disappear.
We need:
- to grey out or in some way differentiate the completed assignments for the upcoming days (with the check mark constantly present for instance) so users can keep track of what they have completed in the present.
- we're going to need an archival/log page of all completed assignments accessible somewhere, don't know exactly where to put that but I'm thinking the far bottom of the page should be a good candidate.

**Comment by turtleguyyy** [comment]
Made them grey out after initially clicking the check, but on refresh, they will no longer be there. If we want to permanently style them differently, we'll have to change the way the lists work a bit. Thoughts?

**Comment by olivierlacan** [comment]
I like this issue. It's the same philosophical (follow me here) debate we had when we would erase bullets on the whiteboard instead of striking them out when we were done.

As far as productivity goes, you feel reinforced by the accomplishments you've done so far. So seeing the stuff you check off already would be very positive. Except the upcoming row includes not only today, but tomorrow and the day after tomorrow. Which means that if by any chance you complete a task for one of these 2 following days before they are due then those tasks would be sticking there in your upcoming panel at worst for 2 days longer. Which would be odd.

Now, odd things have never been a deterrent to me. In this case I think it makes a lot of sense. Even if it goes against some conventions.

That said, should the completed tasks also disappear from the calendars or also be marked accordingly.
I'm also leaning towards keeping them there. 

Ultimately we may decide to leave it up to user preference but it actually involves less processing on our part since we don't have to parse what is completed and what isn't into separate instance variables in the controller. We can simply use the assignment's properties to determine how they should be styled (active/completed/confirmed).

Eager to know what you think.

**Comment by fullsailor** [comment]
I think there are some interesting heuristics we could apply to this problem.

``` gherkin
Given a task is due today
When I mark it as completed
Then I should see it grayed out
And it should be archived at the end of the day.

Given a task is past due
When I mark it as complete
Then I should see it grayed out
And it should be archived immediately

Given a task is due in the future
When I mark it as complete
Then I should see it grayed out
And it should not be auto archived until its due date at midnight

Given any task
When I mark it as complete
Then I should be able to archive it immediately.
```

**Comment by turtleguyyy** [comment]
Everything but the last is already done. I like it!

**Comment by olivierlacan** [comment]
Agree with all of that, already what we had discussed with Zach I think.
Last one is out of scope until Andrew is allowed to touch code ;-)
