### ISSUE TITLE
Links to assignments#show in past due popover should load inside of it

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#68]
Now I know I'm pushing this one, but wouldn't it be cool if you cleared the popover, loaded the assignment in it where the past assignment list used to be, and simply added a back button to go back to the past due assignments list. All of this while staying in the popover view (saving sooo many clicks around the interface and doing all the data transfer over JSON).

If you pull off that one, I buy you lunch.

**Comment by fullsailor** [comment]
For clarity:

> Given I have past due assignments
> When I click open the past due assignments popover
>   And I click on a past due assignment
> Then the the past due assignment should open in the same popover
>   And I should be a link back to the list of assignments.

Framing new features as a user story will help us understand them better.

**Comment by olivierlacan** [comment]
Like this approach to feature description, except I would push it further and nest the conditionals ;-)

**Comment by fullsailor** [comment]
``` gherkin
Given I have past due assignments
When I click open the past due assignments popover
And I click on a past due assignment
Then the the past due assignment should open in the same popover
And I should be a link back to the list of assignments.
```

My oh my there's a Gherkin filter! :D
