### ISSUE TITLE
It seems that too many AJAX calls load HTML instead of JSON

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#69]
Now I've mentioned this in other issues, but I didn't react when you were discussing the issue with @fullsailor.

Why are you loading HTML pages and then stripping the layout if we have respond_to :json in our controllers? Didn't @fullsailor say that $.load() would work wonders?

Are you using that already? Am I lazy and not checking the codebase? Are there unicorns in my bathroom? You can't answer that!

**Comment by turtleguyyy** [comment]
Yes, I am loading HTML. No, i'm not stripping any of it out, Andrew showed me a nifty piece of code that fixes that issue, which is currently residing in our application controller. Neither of the two things had anything to do with the jQuery load method, but yes, I'm using that already too. :)

**Comment by olivierlacan** [comment]
Badass. :-)

**Comment by fullsailor** [comment]
For clarity:

Using `.load(url)` is a great way to replace some elements contents with that of the html contents of a url.

A caveat is that everything on the page will be inserted into the element, which will cause nasty things to happen with double style/script/head tags. So to combat that, we add some nifty ruby code to conditionally render with layout.

``` ruby
class ApplicationController < ActionController::Base
  layout proc { |controller| controller.request.xhr? ? false : 'application' }
end
```

Whenever the controller has to decide if it needs to render the layout, it will pass itself into that to get an answer:

``` ruby
# pseudocode
def render_with_layout
  if @layout.respond_to? :call
     @layout.call(self)
  else
     @layout
  end
end
```
