### ISSUE TITLE
Newcomer guidance

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#71]
I think we're going to need something like what we made for Feedpage to invite the user in on the first sign in (we have that data on the user model). I like what SoundCloud does a lot.

![Screenshot](http://f.cl.ly/items/220H2S3c2o3o3B0j2d1N/Screen%20shot%202011-05-20%20at%202.21.00%20AM.png)

**Comment by olivierlacan** [comment]
# Screen 1

![](http://f.cl.ly/items/1y100K0h1o2K3B180v3j/Screen%20shot%202011-05-30%20at%209.49.03%20AM.png)

# Screen 2

![](http://f.cl.ly/items/2m251N2K2m0U071n1c0h/Screen%20shot%202011-05-30%20at%209.48.08%20AM.png)

# Screen 3

![](http://f.cl.ly/items/1M0U1F2a1k21371v3p2M/Screen%20shot%202011-05-30%20at%209.50.00%20AM.png)

I need to shove the missing name in there for new users who sign in without Twitter, Facebook or Google since it comes up empty in the autocomplete when creating the first assignment and its very confusing.

**Comment by fullsailor** [comment]
Did you intend to reopen this issue?

**Comment by olivierlacan** [comment]
Wasn't complete, still need to revamp the videos and smooth out the kinks.

**Comment by olivierlacan** [comment]
Let's consider this done for now.
