### ISSUE TITLE
Should the rewards be announced in the header too?

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#75]
I feel like this is the next logical step in our corkboard UI evolution. But I'm afraid of cluttering up the header for no reason.
Tell me what you think.

The reason I want to show rewards given on certain actions is so that users discover the achievement system naturally. Ideally a reward icon similar to the house, confirm and past due icons now would light up when you start receiving rewards and say "6 new rewards" on hover. That would be rewards for the current browser session, we can store those in a cookie (see [this](http://railscasts.com/episodes/224-controllers-in-rails-3) for an explanation on how to achieve this). When the user quits his browser, this rewards counter is reset and disappears.

Clicking on the button itself would display the list currently visible at /rewards

A similar behavior should be implemented with Achievements eventually, with the final icon to add on the header (e.g. trophy).

**Comment by fullsailor** [comment]
> When the user quits his browser

If you want this functionality use `session[key]` not `cookies[key]` 

I would instead consider adding a `viewed` field that gets updated when they view the reward/achievement. People are going to expect it to work like the Facebook icon notifications.

**Comment by olivierlacan** [comment]
Good point.
