### ISSUE TITLE
Need to be able to "uncheck" completed assignments

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#78]
Once assignments are greyed out and marked as complete, a user should be able to undo that action (since it's so easy to do by accident). I like this a lot better than someone's suggestion during Friday's meeting that we should put a confirmation dialog before we complete an assignment. Fuck dialogs.

On click the completed_at date should simply be removed from the assignment and the completor_id as well.

**Comment by fullsailor** [comment]
The model I frequently see in todo style applications is:
1. Allow the user to mark as completed.
2. Allow the user to unmark the item.
3. At some point archive all marked items so that the current view is uncluttered.
