### ISSUE TITLE
Webkit validations look weiiiird

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#79]
http://link.olivierlacan.com/6wWS

**Comment by fullsailor** [comment]
Use markdown image tags `![title](link)` so that we can see it without clicking.

![Screenshot](http://f.cl.ly/items/3d250B0z3A0a441c1R37/Screen%20shot%202011-05-22%20at%206.29.28%20AM.png)

**Comment by olivierlacan** [comment]
Tried to use them a few times, would break.

**Comment by olivierlacan** [comment]
Le fixed.
Was a result of not having scoped the flash styles to #flash.
