### ISSUE TITLE
Show "password" in the sign in placeholder

### ISSUE THREAD

**Issue by olivierlacan** [clevercode/roomies#9]
This is a tricky one. Currently the placeholder text in the password field for the sign in form is hidden... because it's a password field. Ideally we would want to show the actual word "password" in there.

So we're going to need to set the password field as a text input by default, and turn it into a password input on focus but have it stay a password input on blur IF there is a value (and not if there's only a placeholder argument).

**Comment by fullsailor** [comment]
Why don't you just use the placeholder attribute. It offers the functionality you are wanting. 

You can provide a graceful degradation later.

**Comment by olivierlacan** [comment]
I was convinced Zach had used placeholder and that it wasn't working, my bad. Assigning this to him.
