### ISSUE TITLE
Everyone's assignments filter doesn't work.

### ISSUE THREAD

**Issue by turtleguyyy** [clevercode/roomies#94]
It does switch the view, but it doesn't include all assignments. 
My Assignments: http://cl.ly/3Q0w2Y2p1W0R2s3z3r3E
Everyone's Assignments: http://cl.ly/1j0a2Y1v28083s0G1m3o

See the issue there?

**Comment by olivierlacan** [comment]
So everyone's assignments is actually everyone else's assignments right?
We can either fix it, or change the label. I'm going to for changing the label.
